chore(ci): Removing sudo

diff --git a/.github/workflows/ci-mac.yaml b/.github/workflows/ci-mac.yaml
--- a/.github/workflows/ci-mac.yaml
+++ b/.github/workflows/ci-mac.yaml
@@ -11,21 +11,25 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
+  pre-clean:
+    if: ${{ ! github.event.pull_request.draft }}
+    runs-on: caf-adaptive-mac
+    steps:
+      - name: Reset OrbStack
+        run: |
+          echo "Resetting OrbStack and deleting all data..."
+          if orb reset -y; then
+            echo "Done"
+          else
+            echo "Failed to reset OrbStack."
+            exit 1
+          fi
+
   create-local-k8s:
-    runs-on: macos-13
-    env:
-      ACTIONS_STEP_DEBUG: true
-      ACTIONS_RUNNER_DEBUG: true
+    runs-on: caf-adaptive-mac
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Download and Install OrbStack via Brew
-        run: |
-          # We are using OrbStack 1.5.1 since the CPU for GitHub shared runners is not supported by later versions.
-          # ARM based runners do not support nested virtualization so we can't install OrbStack on them either.
-          curl -sLo orbstack.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/65da904d37b45eb3f0644e6419ebde37ef927f20/Casks/o/orbstack.rb
-          brew install --cask ./orbstack.rb
 
       - name: Install asdf for macOS
         run: |
@@ -36,8 +40,6 @@ jobs:
           echo .tool-versions
           cut -d' ' -f1 .tool-versions | xargs -I{} asdf plugin-add {} || true
           asdf install
-          orb start
-          sleep 100
           caf_create_local_k8s.sh
           # caf_route_to_local_k8s.sh
 
